{{- if and (eq .Values.workloads.type "deployment") (hasKey .Values.app "deployment") (hasKey .Values "rollout") (hasKey .Values.app "deployment") .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.app.deployment.replicas | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    canary:
      {{- if .Values.rollout.strategy.trafficRouting.enabled }}
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Values.app.name }}-vs
          destinationRule:
            name: {{ .Values.app.name }}-destinationrule
            canarySubsetName: {{ .Values.rollout.strategy.trafficRouting.canarySubsetName | default "canary" }}
            stableSubsetName: {{ .Values.rollout.strategy.trafficRouting.stableSubsetName | default "stable" }}
      {{- end }}
      {{- if .Values.rollout.strategy.steps }}
      steps:
        {{- toYaml .Values.rollout.strategy.steps | nindent 6 }}
      {{- else }}
      steps: []
      {{- end }}
  template:
    {{- include "app.podTemplate" . | nindent 4 }}
{{- end }}
