{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "60m" }}
  secretStoreRef:
    name: eso-secret-store
    kind: SecretStore
  target:
    name: {{ .name }}
    {{- if .K8sSecretType }}
    template:
      type: {{ .K8sSecretType }}
    {{- end }}
  dataFrom:
  - extract:
      key: {{ .secretName }}
{{- end }}
{{- end }}



{{- if and .Values.tlsSecret .Values.tlsSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.tlsSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.tlsSecret.refreshInterval }}
  secretStoreRef:
    name: eso-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.tlsSecret.name }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.tlsSecret.certKey }}
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.tlsSecret.keyKey }}
{{- end }}